auth_app/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'auth_app'
urlpatterns = [
    path('register/', views.register, name='register'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='auth_app/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='auth_app/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='auth_app/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/::w'
         ':wq'
         'Lsdjfklsdadd:',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='auth_app/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

envMonitorSystem/urls.py
from django.contrib import admin
from django.urls import path, include
# from ..auth_app import views
from auth_app import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth_app/', include('auth_app.urls')),
    path('auth_app/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),

]

auth_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)

    class Meta(AbstractUser.Meta):
        pass

auth_app/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

auth_app/views.py
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, redirect

from .forms import RegisterForm


def register(request):
    # 从 get 或者 post 请求中获取 next 参数值
    # get 请求中，next 通过 url 传递，即 /?next=value
    # post 请求中，next 通过表单传递，即 <input type="hidden" name="next" value="{{ next }}"/>
    redirect_to = request.POST.get('next', request.GET.get('next', ''))

    # 只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':
        # request.POST 是一个类字典数据结构，记录了用户提交的注册信息
        # 这里提交的就是用户名（username）、密码（password）、确认密码、邮箱（email）
        # 用这些数据实例化一个用户注册表单
        form = RegisterForm(request.POST)

        # 验证数据的合法性
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

            if redirect_to:
                return redirect(redirect_to)
            else:
                return redirect('/')
    else:
        # 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()

    # 渲染模板
    # 如果用户正在访问注册页面，则渲染的是一个空的注册表单
    # 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    # 将记录用户注册前页面的 redirect_to 传给模板，以维持 next 参数在整个注册流程中的传递
    return render(request, 'auth_app/register.html', context={'form': form, 'next': redirect_to})


def index(request):
    return render(request, 'index.html')

auth_app/templates/auth_app/password_change_done.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>密码修改成功</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
            <p>密码修改成功！</p>
        </div>
    </div>
</div>
</body>
</html>

auth_app/templates/auth_app/password_change_form.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>修改密码</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'index' %}">Django Auth Example</a></h1>
                <h3>修改密码</h3>
                <form class="form" action="{% url 'password_change' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">确认修改</button>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

auth_app/templates/auth_app/password_reset_complete.html
<html>

<head>
    <meta charset="UTF-8">
    <title> Password reset done</title>
    <meta name="description" content="Login - Register Template">
    <meta name="author" content="Lorenzo Angelino aka MrLolok">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {#        <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">#}
    <script type="text/javascript" src="{% static 'rememberme.js' %}"></script>

</head>

<body>
<div class="lines">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
</div>


<div class="topcorner">
    <form>
        <label for="lang-switch">
            <span lang="en">Language</span>
            <span lang="zh">页面语言</span>

        </label>
        <select id="lang-switch">
            <option value="en">English</option>
            <option value="zh" selected>中文</option>
        </select>
    </form>
</div>


<div id="forget-pwd" style="width: 390px !important;">
    <div id="title">
        <a style="text-decoration:none; color: white;">
            <span lang="zh"> 新密码设置成功</span></a>
        <a style="text-decoration:none; color: white;">
            <span lang="en"> New password reset done.</span></a>

    </div>
    </br>
    <span lang="zh">
        新密码已经生效，您现在可以使用新密码进行登录。</br></br>
  </span>
    <span lang="en">
         Your new password is in effect and you can now log in with the new password.</br></br>
  </span>

    <span><a href="{% url 'login' %}"> <input type="submit" id="loginBtn" lang="en" value="Back to Login" autofocus="autofocus"/></a></span>
    <span><a href="{% url 'login' %}"><input type="submit" id="loginBtn" lang="zh" value="返回登录【ENTER】" autofocus="autofocus"/></a></span>


</div>

<!-- 中英文切换JS -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script>
    $('[lang]').hide(); // hide all lang attributes on start.
    $('[lang="zh"]').show(); // show just zhrean text (you can change it)
    $('#lang-switch').change(function () { // put onchange event when user select option from select
        var lang = $(this).val(); // decide which language to display using switch case. The rest is obvious (i think)
        switch (lang) {
            case 'en':
                $('[lang]').hide();
                $('[lang="en"]').show();
                break;
            case 'zh':
                $('[lang]').hide();
                $('[lang="zh"]').show();
                break;
            default:
                $('[lang]').hide();
                $('[lang="zh"]').show();
        }
    });
</script>

<div style="font-size: small; position: absolute; bottom: 10px; right: 10px;"> All Rights Reserved © 2021 by AGou-ops.
</div>

</body>

</html>

auth_app/templates/auth_app/password_reset_confirm.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>set new password</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
    <style>
        .errorlist {
            color: red;
        }
    </style>
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div class="flex-center">
            <div class="unit-1-2 unit-1-on-mobile">
                <h1><a href="{% url 'index' %}">>> EMS Home Page</a></h1>
                <h3>设置新密码</h3>
                <form class="form" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">提交</button>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

auth_app/templates/auth_app/password_reset_done.html
<html>

<head>
    <meta charset="UTF-8">
    <title>Forget password</title>
    <meta name="description" content="Login - Register Template">
    <meta name="author" content="Lorenzo Angelino aka MrLolok">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {#        <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">#}
    <script type="text/javascript" src="{% static 'rememberme.js' %}"></script>

</head>

<body>
<div class="lines">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
</div>


<div class="topcorner">
    <form>
        <label for="lang-switch">
            <span lang="en">Language</span>
            <span lang="zh">页面语言</span>

        </label>
        <select id="lang-switch">
            <option value="en">English</option>
            <option value="zh" selected>中文</option>
        </select>
    </form>
</div>


<div id="forget-pwd" style="width: 390px !important;">
    <div id="title">
        <a style="text-decoration:none; color: white;">
            <span lang="zh"> 密码重置链接已经发送</span></a>
        <a style="text-decoration:none; color: white;">
            <span lang="en"> Your password reset link has been sent.</span></a>

    </div>
    </br>
    <span lang="zh">
        <ul><li>如果您输入的邮件地址所对应的账户存在，设置密码的提示已经发送邮件给您，您将很快收到。</li>
            </br>
            <li> 如果你没有收到邮件, 请确保您所输入的地址是正确的, 并检查您的垃圾邮件文件夹。</li></ul>
        </br>  </span>
    <span lang="en">
<ul><li>If the account corresponding to the e-mail address you entered exists, the prompt to set the password has been sent to you by e-mail, and you will receive it soon.</li>
    </br>
    <li>        If you do not receive the email, please make sure that the address you entered is correct, and check your spam folder.</li></ul>
           </span>

</div>

<!-- 中英文切换JS -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script>
    $('[lang]').hide(); // hide all lang attributes on start.
    $('[lang="zh"]').show(); // show just zhrean text (you can change it)
    $('#lang-switch').change(function () { // put onchange event when user select option from select
        var lang = $(this).val(); // decide which language to display using switch case. The rest is obvious (i think)
        switch (lang) {
            case 'en':
                $('[lang]').hide();
                $('[lang="en"]').show();
                break;
            case 'zh':
                $('[lang]').hide();
                $('[lang="zh"]').show();
                break;
            default:
                $('[lang]').hide();
                $('[lang="zh"]').show();
        }
    });
</script>

<div style="font-size: small; position: absolute; bottom: 10px; right: 10px;"> All Rights Reserved © 2021 by AGou-ops.
</div>

</body>

</html>

auth_app/templates/auth_app/password_reset_form.html
<html>

<head>
    <meta charset="UTF-8">
    <title>Forget password</title>
    <meta name="description" content="Login - Register Template">
    <meta name="author" content="Lorenzo Angelino aka MrLolok">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {#        <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">#}
    <script type="text/javascript" src="{% static 'rememberme.js' %}"></script>

</head>

<body>
<div class="lines">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
</div>


<div class="topcorner">
    <form>
        <label for="lang-switch">
            <span lang="en">Language</span>
            <span lang="zh">页面语言</span>

        </label>
        <select id="lang-switch">
            <option value="en">English</option>
            <option value="zh" selected>中文</option>
        </select>
    </form>
</div>


<div id="forget-pwd">
    <div id="title">
        <a  style="text-decoration:none; color: white;">
            <span lang="zh"> 找回密码</span></a>
        <a  style="text-decoration:none; color: white;">
            <span lang="en"> Forget password</span></a>

    </div>


    <form class="form" action="{% url 'password_reset' %}" method="post">
        {% csrf_token %}

        输入您注册的邮箱地址以找回密码。
        <div class="input">
            <div class="input-addon">
                <i class="material-icons">email</i>
            </div>
            <input type="email" placeholder="E-mail adress" name="email" autocomplete="email" maxlength="254"
                   required="" id="id_email">
        </div>



        {% for field in form %}
{#            {{ field.label_tag }}#}
            {#            {{ field }}#}
            {{ field.errors }}
            {#            {% if field.help_text %}#}
            {#                <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
            {#            {% endif %}#}
        {% endfor %}
    </br>
        <span><input type="submit" lang="en" value="Submit" autofocus="autofocus"/></span>
        <span><input type="submit" lang="zh" value="提交【ENTER】" autofocus="autofocus"/></span>
        <!-- <input type="hidden" name="next" value="{{ next }}"/> -->

    </form>

</div>


<!-- 中英文切换JS -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script>
    $('[lang]').hide(); // hide all lang attributes on start.
    $('[lang="zh"]').show(); // show just zhrean text (you can change it)
    $('#lang-switch').change(function () { // put onchange event when user select option from select
        var lang = $(this).val(); // decide which language to display using switch case. The rest is obvious (i think)
        switch (lang) {
            case 'en':
                $('[lang]').hide();
                $('[lang="en"]').show();
                break;
            case 'zh':
                $('[lang]').hide();
                $('[lang="zh"]').show();
                break;
            default:
                $('[lang]').hide();
                $('[lang="zh"]').show();
        }
    });
</script>

<div style="font-size: small; position: absolute; bottom: 10px; right: 10px;"> All Rights Reserved © 2021 by AGou-ops.
</div>

</body>

</html>

auth_app/templates/auth_app/register.html
<html>

<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <meta name="description" content="Login - Register Template">
    <meta name="author" content="Lorenzo Angelino aka MrLolok">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body>
<div class="lines">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
</div>


<div class="topcorner">
    <form>
        <label for="lang-switch">
            <span lang="en">Language</span>
            <span lang="zh">页面语言</span>

        </label>
        <select id="lang-switch">
            <option value="en">English</option>
            <option value="zh" selected>中文</option>
        </select>
    </form>
</div>


<div id="container-register">
    <div id="title">
        {#        <i class="material-icons lock">lock</i>#}
        <span lang="en"> Register</span>
        <span lang="zh"> 账户注册</span>
    </div>

    <form class="form" action="{% url 'auth_app:register' %}" method="post">
        {% csrf_token %}

        <div class="clearfix"></div>

        <div class="input">
            <div class="input-addon">
                <i class="material-icons">face</i>
            </div>
            <input title="请输入您的用户名" id="id_username" name="username" maxlength="150" autocapitalize="none" placeholder="Username"
                   type="text" required class="validate" autocomplete="off">

        </div>

        <div class="input">
            <div class="input-addon">
                <i class="material-icons">email</i>
            </div>
            <input title="请输入您的电子邮件" type="email" name="email" maxlength="254" placeholder="E-mail" id="id_email" autocomplete="off"
                   required class="validate">

        </div>

        <div class="clearfix"></div>

        <div class="input">
            <div class="input-addon">
                <i class="material-icons">vpn_key</i>
            </div>
            <input title="请输入您的密码" id="id_password1" placeholder="Password" type="password" name="password1" required class="validate"
                   autocomplete="new-password"/>
        </div>

        <div class="input">
            <div class="input-addon">
                <i class="material-icons">vpn_key</i>
            </div>
            <input title="请再次输入您的密码" id="id_password2" placeholder=" Re-input your Password" type="password" name="password2" required
                   class="validate"
                   autocomplete="new-password"/>
        </div>

        <div class="remember-me">
            <input type="checkbox">
            <span style="color: #DDD" lang="en">I accept Terms of Service</span>
            <span style="color: #DDD" lang="zh">我接受隐私协议</span>
        </div>

        {% for field in form %}
{#            {{ field.label_tag }}#}
{#            {{ field }}#}
            {{ field.errors }}
{#            {% if field.help_text %}#}
{#                <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#            {% endif %}#}
        {% endfor %}
        <span lang="en"><input type="submit" value="Register" autofocus/></span>
        <span lang="zh"><input type="submit" value="注册【ENTER】" autofocus/></span>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>

    <div class="privacy">
        <span lang="en"><a href="#">Privacy Policy</a></span>
        <span lang="zh"><a href="#">隐私策略</a></span>
    </div>

    <div class="register">
        <span lang="en">Do you already have an account?</span>
        <span lang="zh">已有账户？</span>
        <a href="#">
            <a href="{% url 'login' %}"> <span lang="en"><button id="register-link">Log In here</button></span></a>
            <a href="{% url 'login' %}"> <span lang="zh"> <button id="register-link">点击登录</button> </span></a>
        </a>
    </div>
</div>


<!-- 中英文切换JS -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script>
    $('[lang]').hide(); // hide all lang attributes on start.
    $('[lang="zh"]').show(); // show just zhrean text (you can change it)
    $('#lang-switch').change(function () { // put onchange event when user select option from select
        var lang = $(this).val(); // decide which language to display using switch case. The rest is obvious (i think)
        switch (lang) {
            case 'en':
                $('[lang]').hide();
                $('[lang="en"]').show();
                break;
            case 'zh':
                $('[lang]').hide();
                $('[lang="zh"]').show();
                break;
            default:
                $('[lang]').hide();
                $('[lang="zh"]').show();
        }
    });
</script>

<div style="font-size: small; position: absolute; bottom: 10px; right: 10px;"> All Rights Reserved © 2021 by AGou-ops.
</div>

</body>

</html>

auth_app/templates/index.html
<html>

<head>
    <meta charset="UTF-8">
    <title>Environmental Monitoring System</title>
    <meta name="description" content="Login - Register Template">
    <meta name="author" content="Lorenzo Angelino aka MrLolok">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {#        <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">#}
        <script type="text/javascript" src="{% static 'rememberme.js' %}"></script>

</head>

<body>
<div class="lines">
    <div class="line"></div>
    <div class="line"></div>
    <div class="line"></div>
</div>


<div class="topcorner">
    <form>
        <label for="lang-switch">
            <span lang="en">Language</span>
            <span lang="zh">页面语言</span>

        </label>
        <select id="lang-switch">
            <option value="en">English</option>
            <option value="zh" selected>中文</option>
        </select>
    </form>
</div>

{% if user.is_authenticated %}

    <div style="
        display: table-cell;
        width: 100%;
        height: 100%;
        padding: 10px;
        border: 3px dashed #1c87c9;
        vertical-align: middle;
        text-align: center;
        z-index:-1;
        position: relative;
">

        <h2 lang="zh">您已登录, 你的用户名为 <font color="red">{{ user.username }}</font>。</h2> </br>
        <h2 lang="en">You are already logged in, and your username is <font color="red">{{ user.username }}</font>
        </h2> </br>
    </div>


{% else %}
    {#        <p>你还没有登录，请#}
    {#            <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a>#}
    {#            </button>#}
    {#            或者#}
    {#            <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a>#}
    {#            </button>#}
    {#        </p>#}

    <div id="container-login">
        <div id="title">
            {#            <i class="material-icons lock">lock</i>#}
            <a href="{% url 'index' %}" style="text-decoration:none; color: white;">
                <span lang="zh"> 环境监测管理系统</span></a>
            <a href="{% url 'index' %}" style="text-decoration:none; color: white;">
                <span lang="en"> EMS Login</span></a>

        </div>


        <form class="form" action="{% url 'login' %}" method="post">
            {% csrf_token %}

            <div class="input">
                <div class="input-addon">
                    <i class="material-icons">face</i>
                </div>

                <input name="username" placeholder="Username" type="text" required class="validate" autocomplete="off"
                       id="id_username"/>
            </div>

            <div class="clearfix"></div>

            <div class="input">
                <div class="input-addon">
                    <i class="material-icons">vpn_key</i>
                </div>
                <input name="password" placeholder="password" type="password" required class="validate"
                       autocomplete="off" id="id_password">
            </div>

            <div class="remember-me">
                <input type="checkbox" id="rememberMe">
                <span style="color: #DDD" lang="en">Remember Me</span>
                <span style="color: #DDD" lang="zh">记住我</span>
            </div>

            {% for field in form %}
                {{ field.label_tag }}
                {#            {{ field }}#}
                {{ field.errors }}
                {#            {% if field.help_text %}#}
                {#                <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
                {#            {% endif %}#}
            {% endfor %}
            <span><input type="submit" id="loginBtn" lang="en" value="Login" autofocus="autofocus"/></span>
            <span><input type="submit" id="loginBtn"lang="zh" value="登入【ENTER】" autofocus="autofocus"/></span>
            <input type="hidden" name="next" value="{{ next }}"/>

        </form>
        <div class="forgot-password">
            <span lang="en"><a href="{% url 'password_reset' %}">💔Forgot your password?</a></span>
            <span lang="zh"><a href="{% url 'password_reset' %}">💔忘记密码？</a></span>

        </div>


        <div class="register">
            <span lang="en">  Don't have an account yet?</span>
            <span lang="zh">  你不会还没有账户吧？</span>
            <a href="{% url 'auth_app:register' %}">
                <span lang="en"><button
                        id="register-link">Register here</button></span>
                <span lang="zh"><button
                        id="register-link">立即注册</button></span>
            </a>
        </div>
        <div class="privacy">
            <span lang="en"> <a href="#">Privacy Policy</a></span>
            <span lang="zh"> <a href="#">隐私策略</a></span>
        </div>
    </div>

{% endif %}




<!-- 中英文切换JS -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script>
    $('[lang]').hide(); // hide all lang attributes on start.
    $('[lang="zh"]').show(); // show just zhrean text (you can change it)
    $('#lang-switch').change(function () { // put onchange event when user select option from select
        var lang = $(this).val(); // decide which language to display using switch case. The rest is obvious (i think)
        switch (lang) {
            case 'en':
                $('[lang]').hide();
                $('[lang="en"]').show();
                break;
            case 'zh':
                $('[lang]').hide();
                $('[lang="zh"]').show();
                break;
            default:
                $('[lang]').hide();
                $('[lang="zh"]').show();
        }
    });
</script>

<div style="font-size: small; position: absolute; bottom: 10px; right: 10px;"> All Rights Reserved © 2021 by AGou-ops.
</div>

</body>

</html>